
## Contexte {.smaller}

- De plus en plus de modèle ML sont voués à être [**mis en production**]{.orange} à l'Insee cf @rapport2024IG
    - [**Multiples cas d'usages de codification**]{.orange} : COICOP, NA2008, PCS2020, APE
    - 🎯 Présentation axée sur l'Activité Principale Exercée (APE) des entreprises
- Révision de la Nomenclature d'Activités Française (NAF):
    - Adaptation au nouveau paysage économique 
    - coordination avec la révision européenne de la NACE
- Des innovations d'autres INS sur la recodification par LLM notamment @ClassifAI
- Concurrence forte et mondiale dans le secteur de l'IA générative: course au _compute_ et aux données cf l'essai de @thebitterlesson, 
- Littérature **abondante** et en plein essor: @rag_paper, @cag_paper, @structuredrag, @hierarchicalrag

::: notes
Aujourd’hui, de plus en plus de modèles de machine learning sont mis en production à l’Insee.
Ils servent à des cas d’usage variés, notamment la codification : COICOP, NA2008, PCS2020, et l’APE, notre focus du jour.

L’APE, ou Activité Principale Exercée, repose sur la NAF, la Nomenclature d’Activités Française. La NAF a récemment été révisée pour mieux refléter le paysage économique actuel et s’aligner avec la révision européenne, la NACE.

Nous ne sommes pas les seuls concernés : d’autres INS expérimentent également la recodification à l’aide de Large Language Models, ou LLM.
Et comme vous le savez, dans le domaine de l’IA générative, la course est mondiale : nouveaux modèles, plus de puissance de calcul, plus de données. Pour comprendre cette dynamique, vous pouvez consulter l’essai de Sutton, The Bitter Lesson.
La littérature sur l’usage des LLM est aujourd’hui abondante, ce qui nous fournit une base solide pour l’état de l’art.
:::

## [La source des données d'entreprises et des libellés d'activités]{.r-fit-text} {.nonincremental auto-animate=true .smaller}

::: {.callout-note icon=false}

## Loi PACTE
À partir du 1er janvier 2023, l’ensemble des formalités d’entreprise doit être déposé en ligne auprès d’un [**organisme unique**]{.orange}.
:::

::: notes
Pour comprendre comment l’APE est codifié, il faut d’abord savoir d’où viennent les libellés d’activité des entreprises.
Tout commence avec la loi PACTE. Depuis janvier 2023, toutes les formalités d’entreprise doivent être déposées en ligne auprès d’un organisme unique, le Guichet Unique.
:::

. . .

INPI = _Institut National de la Propriété Industrielle_

- Office des brevets 
- Opérateur du [**Guichet Unique des Entreprises (GUE)**]{.orange}

::: notes
Dans ce contexte, un nouvel acteur entre en scène : l’INPI.
Loin de se limiter aux brevets ou à la propriété industrielle, il gère désormais le portail du Guichet Unique, qui devient la source principale des déclarations pour le répertoire Sirene.
:::

. . .

- [**Principal flux d'alimentation**]{.orange} des déclarations du répertoire Sirene 
- Fin des Centre de Formalités des Entreprises (CFE)  
➡️ description libre du libellé d'activité: [**texte non-structuré**]{.orange}

  <details> 
  <summary> 
      <font size=3 color=black><b>Afficher un exemple de libellé d'activité</b></font> 
  </summary>

  ```
 Je souhaite développer dans le nettoyage et entretien des bureaux d'entreprise : changelent de poubelles , aspirateur, serpillère
  ```

  </details>

::: notes
La mise en place du portail change la donne.
Aujourd’hui, le répertoire Sirene dépend de l’INPI pour fournir les données nécessaires à l’attribution du code APE.

Avant, les déclarants passaient par plusieurs Centres de formalités : leurs libellés d’activité étaient guidés, relus et en grande partie normalisés.
Maintenant, avec le Guichet unique, chaque déclarant décrit librement son activité principale avec toutes les conséquences que cela entraîne sur la qualité du contenu saisi.
:::


## [Le répertoire Sirene]{.r-fit-text} {.nonincremental auto-animate=true .scrollable .smaller}

Sirene = _Système Informatique pour le Répertoire des Entreprises et de leurs Établissements_

- Répertoire [**de référence**]{.orange} historique gérant le cycle de vie des entreprises 
- garant du SIREN, SIRET [**et**]{.orange} de l'APE basé sur la NAF
- Bascule de Sirene 3 à [**Sirene 4**]{.orange} ➡️ traitement [**en flux**]{.blue2}
- Sicore inefficient face au volume à traiter et particulièrement [**diversité**]{.orange} des libellés 

::: notes
On peut se demander quel est le rôle ou simplement qu'est ce que Sirene dans ce contexte.
Depuis les années 70, Sirene est le répertoire de référence qui suit la vie des entreprises, de leur création à leur cessation, parfois même leur réactivation. Il attribue le SIREN, le SIRET et le fameux code APE, celui que vous voyez sur vos tickets de caisse. 

L’année dernière, Sirene a connu une refonte historique : fini le monde du tout par batch, où le déclarant devait attendre le prochain traitement. Aujourd’hui, tout se fait en flux continu, quasi en temps réel. À l’instant où je vous parle, des entreprises sont en train d’être enregistrées.

Dans ce contexte, avec un volume élevé et une grande variété de libellés, l’ancien système expert Sicore ne suffisait plus : il surchargeait les équipes et ne permettait de codifier que 30 % des cas.
:::

. . .

➡️ Mis en place d'un modèle d'apprentissage supervisé fin d'année 2022.

::: notes
Fin 2022, un classifieur supervisé, basé sur le machine learning, a été mis en place, permettant d’automatiser au moins 65 % du codage du code APE, avec une démarche prudente consistant à présenter les autres cas en reprise gestionnaire.
:::

. . .

- évolution dans le temps des activités ou des descriptifs ➡️ dérive des données
- [**Cas extrême**]{.orange} courant pour la statistique publique ➡️ [**changement de nomenclature**]{.blue2}

Malgré l'absence naturelle de données, comment entraîner notre modèle en NAF 2025 ?

::: notes
Un modèle supervisé n’est pertinent que si les données qui l’ont entraîné restent cohérentes avec la réalité.
Or, les activités et leurs descriptifs évoluent avec le temps : c’est ce qu’on appelle la dérive des données. Dans ces situations, il faut réentraîner le modèle.

Un cas extrême, fréquent en statistique publique, se produit lorsqu’il y a un changement de nomenclature, comme avec la NAF.
Autrement dit, les valeurs possibles de notre variable cible (notre Y) changent, rendant les codes précédents obsolètes.

Alors, comment entraîner un modèle sur la NAF 2025, malgré l’absence de données pour cette nouvelle version ? C’est ce que nous allons explorer.
:::
