
## Calendrier pour l'adoption de la nouvelle NAF 🗓️

- Encore en attente de validation pour la diffusion
- Vers une adoption transitoire
- 2025 --> double codification en NAF 2025
  - Sirus : recodification pour fin 2025
  - Sirene : Intégration de la NAF 2025 en flux et d'une infrastructure MLops-compatible
- 2026 --> amélioration de la codification en NAF 2025
- Sirene (diffusion en 2027) : codification en NAF 2025 mais maintien de la codification NAF 2008 (nécessaire pour certaines publications INSEE)


## NAF 2025 : quels changements ? 

- Au niveau 5 : 746 sous classes contre 732 auparavant
- Principalement des éclatements au niveau de la classe (niveau 4) ... mais pas que !
- ??? classes univoques, correspondance 1-pour-1 ➡️ cas idéal !

TODO:
GRAPHIQUE ICI

## NAF 2025 : les cas multivoques

- ??? classes multivoques, correspondance 1-pour-plusieurs ➡️ cas idéal !
- Parmi cest classe combien ont 2 possibilités? 3 ? etc...

TODO:
GRAPHIQUE ICI

- Besoin d'un expert pour déterminer le nouveau code

## Enjeux et besoins multiples

- Besoin de recoder le [**stock**] de liasse de Sirene ➡️ + [**14 millions**]...
- Pouvoir coder le [**flux**] en NAF 2025 ➡️ entraîner un modèle ➡️ besoin d'avoir un [**stock**]
- Modèle en NAF 2008 entrainé sur + [**10 millions**]
- Performance de fastText [**très dépendant**] du nombre de données d'entraînement

## Données à disposition

- Stock Sirene 3 :  ~ 10 millions mais peu adaptées aux nouvelles données
- Stock Sirene 4 : ~ 2.5 millions 
    - Univoques : ??? millions et ??? sous-classes
    - Multivoques : ??? millions et ??? sous-classes
TODO:

- Campagne d'annotation manuelle indispensable

## Campagne d'annotation 

- Lancement d'une campagne d'annotation depuis mi-2024
- Plateforme développée par l'équipe métier 🤔
- Focus sur les données [**multivoques uniques**]
- 🎯 Objectif double :
  - Attribuer un code NAF 2025 🚀
  - Vérifier la qualité du code NAF 2008 🗸

Aujourd'hui, ~ 27k données annotées... insuffisant !