name: Publish slides

on:
  push:
  workflow_dispatch:

jobs:
  publish-website:
      runs-on: ubuntu-latest

      permissions:
        contents: write
      steps:

        - name: Check out repository
          uses: actions/checkout@v3

        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2

        - name: Install R
          uses: r-lib/actions/setup-r@v2
          with:
            r-version: '4.3.1'
            
        - name: Install Minio Client
          run: |
            wget -q https://dl.min.io/client/mc/release/linux-amd64/mc -O /usr/local/bin/mc
            chmod +x /usr/local/bin/mc
            export 
        
        - name: Retrieve stores from s3
          run: |
            export MC_HOST_s3=https://$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY@$AWS_S3_ENDPOINT
            mc cp -r s3/projet-ape/graphs/ slides/data/
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}

        - name: Render and Publish
          uses: quarto-dev/quarto-actions/publish@v2
          with:
            target: gh-pages
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN_CI }